help:-
	(tab(4),write('Available commands:'),nl,
	tab(8),write('start.            :- Start the game!'),nl,
	tab(8),write('help.             :- Show available commands'),nl,
	tab(8),write('quit.             :- Quit the game'),nl,
	tab(8),write('w. a. s. d.       :- Move'),nl,
	tab(8),write('map.              :- Look at the map'),nl,
	tab(8),write('heal.             :- Cure Tokemon in inventory if in gym center'),nl,
	tab(8),write('status.           :- Show your status'),nl,
	tab(8),write('save(Filename).   :- Save your game'),nl,
	tab(8),write('load(Filename).   :- Load previously saved game'),nl,nl,
	tab(4),write('Legends:'),nl,
	tab(8),write('-X = Pagar'),nl,
	tab(8),write('-P = Player'),nl,
	tab(8),write('-G = Gym'),nl).
